package dev.gaius.browser;

/**
 * Keeps a small, stable bytecode target for the few 26.2 world-generation
 * loops that are too deep for the holder-boundary scheduler to preempt.
 *
 * <p>The target classes intentionally call this adapter instead of naming the
 * scheduler directly.  That keeps the deep-worldgen bytecode contract narrow
 * while still routing the pulse through the normal re-entrant scheduler.
 */
public final class BrowserWorldgenDeepCheckpoint {
    /**
     * Deep vanilla loops can execute millions of back-edges while a holder is being generated.
     * Calling the full scheduler on every edge costs more than the work we are trying to bound,
     * especially during the configuration bootstrap.  Keep a cheap per-runtime sample counter
     * and hand one out of every 256 pulses to the scheduler.  The sampled interval is still
     * short enough to break up the observed 26.2 noise/carver loops, while the scheduler owns
     * the actual deadline, network-pressure, and hard-cap decisions.
     */
    private static final int PULSE_SAMPLE_MASK = 255;
    private static int pulseSampleCounter;

    private BrowserWorldgenDeepCheckpoint() {
    }

    public static void checkpoint() {
        // Deep call sites used to invoke the unconditional server-turn checkpoint.  That
        // turned per-block structure/biome lookups into millions of macrotask hops during
        // bootstrap.  Keep the binary entry point for already-patched jars, but make it obey
        // the same sampled, budget-aware path as the new call sites.
        pulse();
    }

    /**
     * Bounded loop pulse for deep vanilla loops. Unlike {@link #checkpoint()}, this
     * only yields when the normal world-generation budget or network pressure says
     * the current slice is due. The adapter keeps the generated bytecode stable and
     * avoids putting the scheduler class name in every deep target.
     */
    public static void pulse() {
        if ((pulseSampleCounter++ & PULSE_SAMPLE_MASK) != 0) {
            return;
        }
        BrowserWorldgenScheduler.pulse();
    }
}
