//! Chunk generation for the Gaius worldgen kernel: the parts of
//! `NoiseBasedChunkGenerator` that the browser runs off the server thread.
//!
//! The Java side exports a generator as an [`ir`] blob after `RandomState`
//! creation (noise router, noises, aquifer and ore vein configuration, surface
//! rules, biome parameter list, block state and biome id tables). A
//! [`Generator`] compiles it once and then answers pure per-chunk jobs:
//!
//! - [`Generator::run_biomes`] runs `ChunkGenerator.createBiomes`;
//! - [`Generator::run_terrain`] runs the density fill with aquifers and ore veins
//!   (`doFill`), optionally followed by the surface rules (26.3 runs both in
//!   `buildTerrain`), producing per-section block states, the two worldgen
//!   heightmaps and the fluid post-processing positions;
//! - [`Generator::run_surface`] runs `buildSurface` on a chunk filled earlier.
//!
//! The surface rules read biomes through `BiomeManager`'s fuzzy zoom, which reaches one quart
//! into the neighbouring chunks. Vanilla reads what those chunks store; a job can carry it
//! ([`TerrainRequest::ring_biomes`], [`Generator::ring_biomes`]) so a neighbour generated by
//! another version or changed with `/fillbiome` gives the same surface as on the Java path.
//!
//! Two density evaluators exist because 26.3 replaced the density function
//! system: [`df32`] compiles the 26.3 sampler graph (float, whole-volume
//! buffers, sampler cache cells) and [`df64`] the 1.21.11 / 26.2 router (double,
//! NoiseChunk cell interpolation). Carvers, blending, below-zero retrogen and
//! everything after the noise step stay on the Java path.
#![deny(unsafe_op_in_unsafe_fn)]
// Lane loops index several parallel buffers (SoA) with one counter.
#![allow(clippy::needless_range_loop)]
// `!(a < b)` keeps Java's NaN behaviour of the vanilla comparison it mirrors.
#![allow(clippy::neg_cmp_op_on_partial_ord)]

pub mod aquifer;
pub mod arena;
pub mod beard;
pub mod biome;
pub mod chunk;
pub mod climate;
pub mod df32;
pub mod df64;
pub mod generator;
pub mod ir;
pub mod java;
pub mod noises;
pub mod simd;
pub mod surface;
pub mod volume;

pub use generator::{Generator, RingError, TerrainRequest, TerrainResult};
pub use ir::{Ir, IrError};
