package dev.gaius.tools;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.jar.JarEntry;
import java.util.jar.JarFile;
import org.objectweb.asm.ClassReader;
import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.tree.AbstractInsnNode;
import org.objectweb.asm.tree.ClassNode;
import org.objectweb.asm.tree.FieldInsnNode;
import org.objectweb.asm.tree.InsnList;
import org.objectweb.asm.tree.MethodInsnNode;
import org.objectweb.asm.tree.MethodNode;
import org.objectweb.asm.tree.VarInsnNode;

/** Adds opt-in first-successful-draw telemetry to both supported client profiles. */
public final class MinecraftChunkDrawTelemetryPatcher {
    private static final String LEVEL_RENDERER =
            "net/minecraft/client/renderer/LevelRenderer.class";
    private static final String GL_COMMAND_ENCODER =
            "com/mojang/blaze3d/opengl/GlCommandEncoder.class";
    private static final String TELEMETRY_OWNER =
            "dev/gaius/browser/BrowserChunkDrawTelemetry";
    private static final String DRAW_OWNER =
            "com/mojang/blaze3d/systems/RenderPass$Draw";

    private MinecraftChunkDrawTelemetryPatcher() {
    }

    public static void main(String[] args) throws Exception {
        if (args.length != 3) {
            throw new IllegalArgumentException(
                    "usage: <1.21.11|26.2> <input.jar> <output-root>");
        }
        ProfileShape shape = ProfileShape.forId(args[0]);
        Path outputRoot = Path.of(args[2]);
        try (JarFile jar = new JarFile(args[1])) {
            writeClass(
                    outputRoot.resolve(LEVEL_RENDERER),
                    patchLevelRenderer(readEntry(jar, LEVEL_RENDERER), shape));
            writeClass(
                    outputRoot.resolve(GL_COMMAND_ENCODER),
                    patchGlCommandEncoder(readEntry(jar, GL_COMMAND_ENCODER), shape));
        }
        System.out.println("CHUNK_DRAW_TELEMETRY_PATCH_OK profile=" + args[0]
                + " levelMappings=1 lambdaArms=1 drawBegins=1 drawCommits=1");
    }

    private static byte[] patchLevelRenderer(byte[] bytes, ProfileShape shape) {
        ClassNode node = readClass(bytes);
        MethodNode prepare = find(node, "prepareChunkRenders", shape.prepareDescriptor);
        MethodNode lambda = find(node, shape.lambdaName, shape.lambdaDescriptor);

        InsnList begin = new InsnList();
        // The identity field is profile-specific.  1.21.11 stores the active
        // ClientLevel on LevelRenderer, while 26.2 moved that state to the
        // renderer's LevelRenderState.  Keep the read on LevelRenderer itself
        // so the generated bytecode never reaches across a private field in
        // GameRenderer; TeaVM then sees a valid field for both class shapes.
        begin.add(new VarInsnNode(Opcodes.ALOAD, 0));
        begin.add(new FieldInsnNode(
                Opcodes.GETFIELD,
                "net/minecraft/client/renderer/LevelRenderer",
                shape.identityFieldName,
                shape.identityFieldDescriptor));
        begin.add(new MethodInsnNode(
                Opcodes.INVOKESTATIC,
                TELEMETRY_OWNER,
                "beginPrepare",
                "(Ljava/lang/Object;)V",
                false));
        prepare.instructions.insert(begin);

        VarInsnNode uniformStore = null;
        for (AbstractInsnNode instruction : prepare.instructions.toArray()) {
            if (!(instruction instanceof VarInsnNode store)
                    || store.getOpcode() != Opcodes.ISTORE
                    || store.var != shape.uniformIndexLocal) {
                continue;
            }
            AbstractInsnNode previous = previousOpcode(store);
            if (previous instanceof MethodInsnNode call
                    && call.name.equals("size")
                    && call.desc.equals("()I")) {
                if (uniformStore != null) {
                    throw new IllegalStateException("multiple guarded uniform-index stores");
                }
                uniformStore = store;
            }
        }
        if (uniformStore == null) {
            throw new IllegalStateException("uniform-index List.size() -> ISTORE shape changed");
        }
        InsnList register = new InsnList();
        register.add(new VarInsnNode(Opcodes.ILOAD, shape.uniformIndexLocal));
        register.add(new VarInsnNode(Opcodes.ALOAD, shape.blockPosLocal));
        register.add(new MethodInsnNode(
                Opcodes.INVOKEVIRTUAL,
                "net/minecraft/core/BlockPos",
                "getX",
                "()I",
                false));
        register.add(new VarInsnNode(Opcodes.ALOAD, shape.blockPosLocal));
        register.add(new MethodInsnNode(
                Opcodes.INVOKEVIRTUAL,
                "net/minecraft/core/BlockPos",
                "getZ",
                "()I",
                false));
        register.add(new MethodInsnNode(
                Opcodes.INVOKESTATIC,
                TELEMETRY_OWNER,
                "registerSection",
                "(III)V",
                false));
        prepare.instructions.insert(uniformStore, register);

        AbstractInsnNode callbackReturn = null;
        for (AbstractInsnNode instruction : lambda.instructions.toArray()) {
            if (instruction.getOpcode() == Opcodes.RETURN) {
                if (callbackReturn != null) {
                    throw new IllegalStateException("multiple ChunkSection callback returns");
                }
                callbackReturn = instruction;
            }
        }
        if (callbackReturn == null) {
            throw new IllegalStateException("ChunkSection callback return was not found");
        }
        InsnList arm = new InsnList();
        arm.add(new VarInsnNode(Opcodes.ILOAD, 0));
        arm.add(new MethodInsnNode(
                Opcodes.INVOKESTATIC,
                TELEMETRY_OWNER,
                "armUniformIndex",
                "(I)V",
                false));
        lambda.instructions.insertBefore(callbackReturn, arm);
        return writeClass(node);
    }

    private static byte[] patchGlCommandEncoder(byte[] bytes, ProfileShape shape) {
        ClassNode node = readClass(bytes);
        MethodNode execute = find(node, "executeDrawMultiple", shape.executeDescriptor);
        MethodInsnNode callbackAccessor = null;
        MethodInsnNode callbackAccept = null;
        MethodInsnNode drawCall = null;
        for (AbstractInsnNode instruction : execute.instructions.toArray()) {
            if (!(instruction instanceof MethodInsnNode call)) {
                continue;
            }
            if (call.owner.equals(DRAW_OWNER)
                    && call.name.equals("uniformUploaderConsumer")
                    && call.desc.equals("()Ljava/util/function/BiConsumer;")) {
                if (callbackAccessor != null) {
                    throw new IllegalStateException("multiple draw callback accessors");
                }
                callbackAccessor = call;
            } else if (call.owner.equals("java/util/function/BiConsumer")
                    && call.name.equals("accept")
                    && call.desc.equals("(Ljava/lang/Object;Ljava/lang/Object;)V")) {
                callbackAccept = call;
            } else if (call.getOpcode() == Opcodes.INVOKEVIRTUAL
                    && call.owner.equals("com/mojang/blaze3d/opengl/GlCommandEncoder")
                    && call.name.equals("drawFromBuffers")
                    && call.desc.equals(shape.drawDescriptor)) {
                if (drawCall != null) {
                    throw new IllegalStateException("multiple drawFromBuffers calls");
                }
                drawCall = call;
            }
        }
        if (callbackAccessor == null || callbackAccept == null || drawCall == null
                || !precedes(callbackAccept, drawCall)) {
            throw new IllegalStateException(
                    "executeDrawMultiple callback -> drawFromBuffers shape changed");
        }

        InsnList clear = new InsnList();
        clear.add(new MethodInsnNode(
                Opcodes.INVOKESTATIC,
                TELEMETRY_OWNER,
                "beginDraw",
                "()V",
                false));
        execute.instructions.insertBefore(callbackAccessor, clear);

        InsnList commit = new InsnList();
        commit.add(new VarInsnNode(Opcodes.ALOAD, shape.drawLocal));
        commit.add(new MethodInsnNode(
                Opcodes.INVOKEVIRTUAL,
                DRAW_OWNER,
                "indexCount",
                "()I",
                false));
        commit.add(new MethodInsnNode(
                Opcodes.INVOKESTATIC,
                TELEMETRY_OWNER,
                "commitSuccessfulDraw",
                "(I)V",
                false));
        execute.instructions.insert(drawCall, commit);
        return writeClass(node);
    }

    private static boolean precedes(AbstractInsnNode first, AbstractInsnNode second) {
        for (AbstractInsnNode cursor = first; cursor != null; cursor = cursor.getNext()) {
            if (cursor == second) {
                return true;
            }
        }
        return false;
    }

    private static AbstractInsnNode previousOpcode(AbstractInsnNode instruction) {
        AbstractInsnNode previous = instruction.getPrevious();
        while (previous != null && previous.getOpcode() < 0) {
            previous = previous.getPrevious();
        }
        return previous;
    }

    private static ClassNode readClass(byte[] bytes) {
        ClassNode node = new ClassNode();
        new ClassReader(bytes).accept(node, 0);
        return node;
    }

    private static byte[] writeClass(ClassNode node) {
        ClassWriter writer = new ClassWriter(ClassWriter.COMPUTE_MAXS);
        node.accept(writer);
        return writer.toByteArray();
    }

    private static MethodNode find(ClassNode node, String name, String descriptor) {
        return node.methods.stream()
                .filter(method -> method.name.equals(name) && method.desc.equals(descriptor))
                .findFirst()
                .orElseThrow(() -> new IllegalStateException(
                        node.name + "." + name + descriptor + " was not found"));
    }

    private static byte[] readEntry(JarFile jar, String name) throws IOException {
        JarEntry entry = jar.getJarEntry(name);
        if (entry == null) {
            throw new IOException("missing jar entry: " + name);
        }
        try (InputStream input = jar.getInputStream(entry)) {
            return input.readAllBytes();
        }
    }

    private static void writeClass(Path output, byte[] bytes) throws IOException {
        Files.createDirectories(output.toAbsolutePath().getParent());
        Files.write(output, bytes);
    }

    private record ProfileShape(
            String prepareDescriptor,
            String lambdaName,
            String lambdaDescriptor,
            int blockPosLocal,
            int uniformIndexLocal,
            String executeDescriptor,
            String drawDescriptor,
            int drawLocal,
            String identityFieldName,
            String identityFieldDescriptor) {
        private static ProfileShape forId(String id) {
            String returnType =
                    "Lnet/minecraft/client/renderer/chunk/ChunkSectionsToRender;";
            String lambdaDescriptor =
                    "(I[Lcom/mojang/blaze3d/buffers/GpuBufferSlice;"
                            + "Lcom/mojang/blaze3d/systems/RenderPass$UniformUploader;)V";
            if (id.equals("1.21.11")) {
                return new ProfileShape(
                        "(Lorg/joml/Matrix4fc;DDD)" + returnType,
                        "lambda$prepareChunkRenders$6",
                        lambdaDescriptor,
                        17,
                        20,
                        "(Lcom/mojang/blaze3d/opengl/GlRenderPass;Ljava/util/Collection;"
                                + "Lcom/mojang/blaze3d/buffers/GpuBuffer;"
                                + "Lcom/mojang/blaze3d/vertex/VertexFormat$IndexType;"
                                + "Ljava/util/Collection;Ljava/lang/Object;)V",
                        "(Lcom/mojang/blaze3d/opengl/GlRenderPass;III"
                                + "Lcom/mojang/blaze3d/vertex/VertexFormat$IndexType;"
                                + "Lcom/mojang/blaze3d/opengl/GlRenderPipeline;I)V",
                        8,
                        "level",
                        "Lnet/minecraft/client/multiplayer/ClientLevel;");
            }
            if (id.equals("26.2")) {
                return new ProfileShape(
                        "(Lorg/joml/Matrix4fc;)" + returnType,
                        "lambda$prepareChunkRenders$1",
                        lambdaDescriptor,
                        11,
                        14,
                        "(Lcom/mojang/blaze3d/opengl/GlRenderPass;Ljava/util/Collection;"
                                + "Lcom/mojang/blaze3d/buffers/GpuBuffer;"
                                + "Lcom/mojang/blaze3d/IndexType;Ljava/util/Collection;"
                                + "Ljava/lang/Object;)V",
                        "(Lcom/mojang/blaze3d/opengl/GlRenderPass;III"
                                + "Lcom/mojang/blaze3d/IndexType;"
                                + "Lcom/mojang/blaze3d/opengl/GlRenderPipeline;II)V",
                        8,
                        "levelRenderState",
                        "Lnet/minecraft/client/renderer/state/level/LevelRenderState;");
            }
            throw new IllegalArgumentException("unsupported profile: " + id);
        }
    }
}
