package net.minecraft.world.level.levelgen;

import java.io.DataOutputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import net.minecraft.SharedConstants;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Holder;
import net.minecraft.core.HolderLookup;
import net.minecraft.core.IdMapper;
import net.minecraft.core.QuartPos;
import net.minecraft.core.registries.Registries;
import net.minecraft.data.registries.VanillaRegistries;
import net.minecraft.server.Bootstrap;
import net.minecraft.world.level.ChunkPos;
import net.minecraft.world.level.LevelHeightAccessor;
import net.minecraft.world.level.biome.Biome;
import net.minecraft.world.level.biome.BiomeManager;
import net.minecraft.world.level.biome.MultiNoiseBiomeSource;
import net.minecraft.world.level.biome.MultiNoiseBiomeSourceParameterLists;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.chunk.PalettedContainerFactory;
import net.minecraft.world.level.chunk.ProtoChunk;
import net.minecraft.world.level.chunk.status.ChunkStatus;
import net.minecraft.world.level.chunk.Strategy;
import net.minecraft.world.level.chunk.UpgradeData;
import net.minecraft.world.level.levelgen.blending.Blender;

/**
 * The 26.2 counterpart of the 26.3 {@code WorldgenReference}: writes the vanilla overworld as a
 * worldgen kernel IR ({@link GaiusWorldgenExport262}) plus reference chunks generated by the real
 * {@link NoiseBasedChunkGenerator} steps ({@code createBiomes}, {@code fillFromNoise},
 * {@code buildSurface}) on {@link ProtoChunk}s. Same file layout; the density block is zero
 * (26.2 has no volume sampler to compare against) and the comparison test skips it.
 *
 * <p>It lives in vanilla's package to reach the beardifier marker: each chunk's
 * {@link NoiseChunk} is created up front with no structures, as {@code createNoiseChunk} would
 * for a chunk without structure pieces, so the steps run without a structure manager.
 * Usage: {@code GaiusWorldgenReference262 <seed> <output-directory> [x,z ...]}.
 */
public final class GaiusWorldgenReference262 {
    private static final int MIN_Y = -64;
    private static final int HEIGHT = 384;

    private final HolderLookup.Provider lookup;
    private final NoiseGeneratorSettings settings;
    private final NoiseBasedChunkGenerator generator;
    private final MultiNoiseBiomeSource source;
    private final RandomState randomState;
    private final LevelHeightAccessor height = LevelHeightAccessor.create(MIN_Y, HEIGHT);
    private final PalettedContainerFactory factory;
    private final Aquifer.FluidPicker picker;
    private final Map<Long, ProtoChunk> biomeChunks = new HashMap<>();

    private GaiusWorldgenReference262(HolderLookup.Provider lookup, long seed, IdMapper<Holder<Biome>> biomeMap) {
        this.lookup = lookup;
        Holder<NoiseGeneratorSettings> settingsHolder =
                lookup.lookupOrThrow(Registries.NOISE_SETTINGS).getOrThrow(NoiseGeneratorSettings.OVERWORLD);
        this.settings = settingsHolder.value();
        this.source = MultiNoiseBiomeSource.createFromPreset(lookup
                .lookupOrThrow(Registries.MULTI_NOISE_BIOME_SOURCE_PARAMETER_LIST)
                .getOrThrow(MultiNoiseBiomeSourceParameterLists.OVERWORLD));
        this.generator = new NoiseBasedChunkGenerator(source, settingsHolder);
        this.randomState = RandomState.create(settings, lookup.lookupOrThrow(Registries.NOISE), seed);
        this.factory = new PalettedContainerFactory(
                Strategy.createForBlockStates(Block.BLOCK_STATE_REGISTRY), Blocks.AIR.defaultBlockState(), null,
                Strategy.createForBiomes(biomeMap), biomeMap.byId(0), null);
        int seaLevel = settings.seaLevel();
        Aquifer.FluidStatus lava = new Aquifer.FluidStatus(-54, Blocks.LAVA.defaultBlockState());
        Aquifer.FluidStatus sea = new Aquifer.FluidStatus(seaLevel, settings.defaultFluid());
        this.picker = (x, y, z) -> y < Math.min(-54, seaLevel) ? lava : sea;
    }

    public static void main(String[] args) throws IOException {
        long seed = Long.parseLong(args[0]);
        Path out = Path.of(args[1]);
        Files.createDirectories(out);
        SharedConstants.tryDetectVersion();
        Bootstrap.bootStrap();
        HolderLookup.Provider lookup = VanillaRegistries.createLookup();
        Map<Biome, Integer> biomeIds = new HashMap<>();
        IdMapper<Holder<Biome>> biomeMap = new IdMapper<>();
        lookup.lookupOrThrow(Registries.BIOME).listElements().forEach(h -> {
            biomeIds.put(h.value(), biomeIds.size());
            biomeMap.add(h);
        });
        GaiusWorldgenReference262 reference = new GaiusWorldgenReference262(lookup, seed, biomeMap);
        byte[] ir = GaiusWorldgenExport262.export(reference.generator, reference.randomState, lookup,
                b -> biomeIds.getOrDefault(b, -1), reference.height, seed, 1);
        Files.write(out.resolve("overworld.gwir"), ir);
        System.out.println("overworld.gwir: " + ir.length + " bytes");

        String[] chunks = args.length > 2 ? Arrays.copyOfRange(args, 2, args.length) : new String[] {"0,0", "7,-3"};
        for (String chunk : chunks) {
            String[] xz = chunk.split(",");
            int cx = Integer.parseInt(xz[0]);
            int cz = Integer.parseInt(xz[1]);
            Path file = out.resolve("chunk_" + cx + "_" + cz + ".ref");
            try (DataOutputStream data = new DataOutputStream(Files.newOutputStream(file))) {
                data.writeInt(Integer.reverseBytes(cx));
                data.writeInt(Integer.reverseBytes(cz));
                reference.write(data, cx, cz, biomeIds, seed);
            }
            System.out.println(file.getFileName());
        }
    }

    private ProtoChunk newChunk(int cx, int cz) {
        ProtoChunk chunk = new ProtoChunk(new ChunkPos(cx, cz), UpgradeData.EMPTY, height, factory, null);
        chunk.getOrCreateNoiseChunk(c -> NoiseChunk.forChunk(
                c, randomState, DensityFunctions.BeardifierMarker.INSTANCE, settings, picker, Blender.empty()));
        return chunk;
    }

    /** A chunk with its biomes filled, as a neighbour in the surface step's region. */
    private ProtoChunk biomeChunk(int cx, int cz) {
        return biomeChunks.computeIfAbsent(ChunkPos.pack(cx, cz), key -> {
            ProtoChunk chunk = newChunk(cx, cz);
            generator.createBiomes(randomState, Blender.empty(), null, chunk).join();
            chunk.setPersistedStatus(ChunkStatus.BIOMES);
            return chunk;
        });
    }

    private void write(DataOutputStream data, int cx, int cz, Map<Biome, Integer> biomeIds, long seed)
            throws IOException {
        int volume = 16 * HEIGHT * 16;
        for (int i = 0; i < volume; i++) {
            data.writeInt(0);
        }
        ProtoChunk chunk = newChunk(cx, cz);
        generator.createBiomes(randomState, Blender.empty(), null, chunk).join();
        chunk.setPersistedStatus(ChunkStatus.BIOMES);
        biomeChunks.put(ChunkPos.pack(cx, cz), chunk);
        int minQuartY = QuartPos.fromBlock(MIN_Y);
        for (int section = 0; section < HEIGHT / 16; section++) {
            for (int qy = 0; qy < 4; qy++) {
                for (int qz = 0; qz < 4; qz++) {
                    for (int qx = 0; qx < 4; qx++) {
                        Holder<Biome> b = chunk.getNoiseBiome(
                                (cx << 2) + qx, minQuartY + section * 4 + qy, (cz << 2) + qz);
                        data.writeInt(Integer.reverseBytes(biomeIds.get(b.value())));
                    }
                }
            }
        }

        generator.fillFromNoise(Blender.empty(), randomState, null, chunk).join();
        writeStates(data, chunk, cx, cz);

        // The surface step reads biomes through the region: neighbours' noise biomes, with the
        // quart y clamped like ChunkAccess.getNoiseBiome.
        BiomeManager.NoiseBiomeSource regionBiomes = (qx, qy, qz) -> biomeChunk(qx >> 2, qz >> 2)
                .getNoiseBiome(qx, qy, qz);
        BiomeManager biomeManager = new BiomeManager(regionBiomes, BiomeManager.obfuscateSeed(seed));
        Set<Holder<Biome>> possible = source.possibleBiomes();
        generator.buildSurface(chunk, new WorldGenerationContext(generator, height), randomState, null,
                biomeManager, Blender.empty(), possible);
        writeStates(data, chunk, cx, cz);
        for (Heightmap.Types type : new Heightmap.Types[] {
                Heightmap.Types.WORLD_SURFACE_WG, Heightmap.Types.OCEAN_FLOOR_WG}) {
            for (int z = 0; z < 16; z++) {
                for (int x = 0; x < 16; x++) {
                    data.writeInt(Integer.reverseBytes(chunk.getHeight(type, x, z) + 1));
                }
            }
        }
    }

    /** Block states in the kernel volume order {@code y + (x + z * 16) * height}. */
    private static void writeStates(DataOutputStream data, ProtoChunk chunk, int cx, int cz) throws IOException {
        int[] states = new int[16 * HEIGHT * 16];
        for (int z = 0; z < 16; z++) {
            for (int x = 0; x < 16; x++) {
                for (int y = 0; y < HEIGHT; y++) {
                    states[y + (x + z * 16) * HEIGHT] = Block.BLOCK_STATE_REGISTRY.getId(
                            chunk.getBlockState(new BlockPos((cx << 4) + x, y + MIN_Y, (cz << 4) + z)));
                }
            }
        }
        for (int s : states) {
            data.writeInt(Integer.reverseBytes(s));
        }
    }
}
